artifacts_root: artifacts


data_ingestion:
  root: artifacts/data_ingestion
  source_url: 'https://github.com/chirag-garg9/datasets/raw/main/books.zip'
  local_data_file: artifacts/data_ingestion/books.zip
  unzip_directory: artifacts/data_ingestion

data_validation:
  root: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  all_required_files: ['train', 'test']